### PR TITLE
Move CCPP technical documentation from ccpp-framework repo to ccpp-doc

### PR DESCRIPTION
**Pull request by JulieSchramm**
- Update README.md file
- Add CODEOWNERS file
- Add CCPPtechnical directory from ccpp-framework directory, with modifications to
  point to sample code in _static instead of DevelopersGuide.

HTML and PDF files build and are viewable.

### CODE REVIEW

**Comment by climbfuji** [comment]
@JulieSchramm is this based on ccpp-framework/master or ccpp-framework/gmtb/develop? When did you "copy" the files? Today? If gmtb/develop, after my latest commit went in today? Today - 2019/09/23, commit was early morning (and removed documentation related to the TRANSITION compile option). Thanks!

**Comment by JulieSchramm** [comment]
@climbfuji This PR is based on the ccpp-framework/gmtb/develop branch, which I updated this afternoon.  I did get your last commit from 2019/09/23, with the TRANSITION  compile option removed.  The PR is to ccpp-doc/master from JulieSchramm/master.

**Comment by climbfuji** [comment]
Ok, the question then is whether ccpp-doc master should correspond to the ccpp-framework/master documentation, and gmtb/develop should be a branch in ccpp-doc that matches the gmtb/develop branch of ccpp-framework? @ligiabernardet @llpcarson @grantfirl

**Comment by ligiabernardet** [comment]
I believe the master in ccpp-doc should contain documentation up-to-date with the GMTB "official" code, which is the master of https://github.com/NCAR/NEMSfv3gfs and associated git submodules, as described in https://github.com/NCAR/NEMSfv3gfs/blob/master/.gitmodules.

We should also maintain a gmtb/develop branch in ccpp-doc, containing documentation associated with https://github.com/NCAR/NEMSfv3gfs/blob/gmtb/develop/.gitmodules

**Pull request closed without merging**
