### PR TITLE
ccpp-doc updates pre-v6

### PR DESCRIPTION
**Pull request by climbfuji**
An update of all sections - I read through the entire documentation and changed or flagged everything that I think is wrong or outdated.

Update 2022/04/17 @mkavulich @ligiabernardet @grantfirl 
- I removed all my previous comments (`!!! DH* ...`) and cleaned up how we refer to files in a particular directory structure
- I ran sphinx, attached is the output as `.tar.gz`)

This PR is ready to merge from my side.

[build_html.tar.gz](https://github.com/NCAR/ccpp-doc/files/8502480/build_html.tar.gz)

### CODE REVIEW

**Review by ligiabernardet — APPROVED** [review]
Thank you for this comprehensive update. I did not run Sphinx but the changes look good to me. I think we can merge this PR and later go back to address the comments you made where further updates are still needed. Another option is to remove this comments and enter them in the to-do list located at https://github.com/NCAR/ccpp-doc/issues/49.

**Comment by climbfuji** [comment]
> Thank you for this comprehensive update. I did not run Sphinx but the changes look good to me. I think we can merge this PR and later go back to address the comments you made where further updates are still needed. Another option is to remove this comments and enter them in the to-do list located at #49.

There are many of these `!!! DH*` in the text. They are not treated as comments in doxygen and will thus appear in the output. Not sure if that is what we want.

**Comment by ligiabernardet** [comment]
@mkavulich Given that @climbfuji is out until May 15, how should we proceed with this PR? For example: we could transform the DH comments into issues to be tackled at subsequent PRs, and go ahead and merge this one. Other ideas?

**Comment by climbfuji** [comment]
> @mkavulich Given that @climbfuji is out until May 15, how should we proceed with this PR? For example: we could transform the DH comments into issues to be tackled at subsequent PRs, and go ahead and merge this one. Other ideas?

I fixed all those already - see commit https://github.com/NCAR/ccpp-doc/pull/53/commits/e3d4b8b5cfd913950708a446e7bd7ad4ec0b1ff6. I also updated the PR description on April 17.

**Pull request merged**
